### ISSUE TITLE
Change label

### ISSUE THREAD

**Issue by finzaiko** [thatisuday/node-time-ago#2]
Thanks for great work, I use this really helpful

Can I customize the minutes label ?
2 minutes ago --become--> 2m
2 hours ago --become--> 2h
2 days ago --become--> 2d
and more..

**Comment by thatisuday** [comment]
Yes you can do this, just fork the repo and change the label in `index.js`. It's very simple. Then you can publish to npm registry with your custom package name. I can't do modification in this repo, I want to keep it simple as it is.

**Comment by dandv** [comment]
@finzaiko: look at the [s-ago](https://github.com/sebastiansandqvist/s-ago) module. It supports customizing the output and the thresholds.

**Comment by finzaiko** [comment]
@dandv Great thanks.
