### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by dandv** [thatisuday/node-time-ago#4]
When this repo was created, there already existed a reliable, well-tested and documented module to provide timeago functionality: [s-ago](https://github.com/sebastiansandqvist/s-ago).

Why was this module created? How does it differ from [prior art](http://slides.com/dandv/prior-art#/)?

**Comment by thatisuday** [comment]
Well, I tried all modules and I faced several difficulties. So I create my
personal module for customized to my requirement.
